### ISSUE TITLE
README.md spelling mistake

### ISSUE THREAD

**Issue by ghost** [ChrisTitusTech/zsh#5]
There is a typo in the README.md.

In the first line, under the second point "Setup", you either have to remove the quotation mark or add a second one at the end.

`
touch "$HOME/.cache/zshhistory`

**Comment by prashantnirgun** [comment]
quotes are missing my zshrc file is empty

**Comment by ghost** [comment]
Surely, there's also a mistake:
```
echo 'source ~/powerlevel10k/powerlevel10k.zsh-theme' >>! ~/.zshrc
```
You need to remove the exclamation mark:

```
echo 'source ~/powerlevel10k/powerlevel10k.zsh-theme' >> ~/.zshrc
```

On his site it's the same:
https://christitus.com/zsh/

**Comment by ChrisTitusTech** [comment]
Thanks All, Fixed both the readme and the website.
